### ISSUE TITLE
Crash on 1.18.1 startup

### ISSUE THREAD

**Issue by CozzyBro2** [Wesley1808/ServerCore-Fabric#9] opened 2021-12-10 15:50 UTC
**Describe the bug**
The server crashes on startup, happens with no other mods besides Fabric API, and with my current mod setup.

**Reproduce**
Download version 1.2.6 of servercore, and version 0.44.0+1.18 of Fabric API, and 0.12.9 of the Fabric loader.

**Expected behavior**
The server to startup normally

**Versions** -Latest is not a version!
ServerCore: 1.2.6
Minecraft: 1.18.1
Fabric: 0.12.9
Fabric API: 0.44.0+1.18

**Mod incompatibilities**
List any installed mods you think might play a role in causing this bug.

* Croptopia
* Cloth Config
* Repurposed structures

All of these mods are installed alongside the Fabric API, however none should feasibly conflict.

**Log file**
```
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCaptureh.jar' nogui
[10:43:40] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.9
2021-12-10 10:43:41,562 main ERROR Cannot access RandomAccessFile java.io.FileNotFoundException: logs/latest.log (Permission denied) java.io.FileNotFoundException: logs/latest.log (Permission denied)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:127)
	at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory.createManager(RollingRandomAccessFileManager.java:223)
	at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory.createManager(RollingRandomAccessFileManager.java:195)
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:113)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)
	at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.getRollingRandomAccessFileManager(RollingRandomAccessFileManager.java:109)
	at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender$Builder.build(RollingRandomAccessFileAppender.java:132)
	at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender$Builder.build(RollingRandomAccessFileAppender.java:53)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1000)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:940)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:932)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:551)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:287)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:627)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:700)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:717)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:272)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:245)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:176)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:666)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.getLogger(Log4jLogHandler.java:45)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.log(Log4jLogHandler.java:37)
	at net.fabricmc.loader.impl.util.log.BuiltinLogHandler.replay(BuiltinLogHandler.java:76)
	at net.fabricmc.loader.impl.util.log.Log.init(Log.java:34)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.setupLog4jLogHandler(MinecraftGameProvider.java:518)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:499)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:136)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)

2021-12-10 10:43:41,568 main ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender for element RollingRandomAccessFile: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory@1130520d] unable to create manager for [logs/latest.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$FactoryData@5f77d0f9] java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory@1130520d] unable to create manager for [logs/latest.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$FactoryData@5f77d0f9]
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:115)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)
	at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.getRollingRandomAccessFileManager(RollingRandomAccessFileManager.java:109)
	at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender$Builder.build(RollingRandomAccessFileAppender.java:132)
	at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender$Builder.build(RollingRandomAccessFileAppender.java:53)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1000)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:940)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:932)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:551)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:287)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:627)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:700)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:717)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:272)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:245)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:176)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:666)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.getLogger(Log4jLogHandler.java:45)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.log(Log4jLogHandler.java:37)
	at net.fabricmc.loader.impl.util.log.BuiltinLogHandler.replay(BuiltinLogHandler.java:76)
	at net.fabricmc.loader.impl.util.log.Log.init(Log.java:34)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.setupLog4jLogHandler(MinecraftGameProvider.java:518)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:499)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:136)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)

2021-12-10 10:43:41,570 main ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender for element RollingRandomAccessFile: java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:234)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:134)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1000)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:940)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:932)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:551)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:287)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:627)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:700)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:717)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:272)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:245)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:176)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:666)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.getLogger(Log4jLogHandler.java:45)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.log(Log4jLogHandler.java:37)
	at net.fabricmc.loader.impl.util.log.BuiltinLogHandler.replay(BuiltinLogHandler.java:76)
	at net.fabricmc.loader.impl.util.log.Log.init(Log.java:34)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.setupLog4jLogHandler(MinecraftGameProvider.java:518)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:499)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:136)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)

2021-12-10 10:43:41,572 main ERROR Null object returned for RollingRandomAccessFile in Appenders.
2021-12-10 10:43:41,582 main ERROR Unable to locate appender "File" for logger config "root"
[10:43:41] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.9
[10:43:42] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
 - Mod 'Repurposed Structures' (repurposed_structures) 3.1.8+1.18.0 recommends version 1.0.0 or later of no_null_processors, which is missing!
	 - You should install version 1.0.0 or later of no_null_processors for the optimal experience.
[10:43:42] [main/INFO]: Loading 52 mods:
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.0.45
	- com_electronwill_night-config_core 3.6.4 via servercore-fabric
	- com_electronwill_night-config_toml 3.6.4 via servercore-fabric
	- com_typesafe_config 1.4.1 via confabricate
	- confabricate 2.2.0-SNAPSHOT+4.1.1 via croptopia
	- croptopia 1.7.2
	- fabric 0.44.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cdc8 via fabric
	- fabric-api-lookup-api-v1 1.4.0+16d92c47c8 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a9c8 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d95c8 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cdc8 via fabric
	- fabric-containers-v0 0.1.18+d154e2c6c8 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73dc8 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d95c8 via fabric
	- fabric-dimensions-v1 2.1.7+43d29571c8 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378ac8 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f17c8 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cdc8 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d95c8 via fabric
	- fabric-item-api-v1 1.3.0+691a79b5c8 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d95c8 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca335c8 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d95c8 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d95c8 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cdc8 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d95c8 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cdc8 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842ec8 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d95c8 via fabric
	- fabric-particles-v1 0.2.9+526dc1acc8 via fabric
	- fabric-registry-sync-v0 0.8.5+3ac43d95c8 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d7c8 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d95c8 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d95c8 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d95c8 via fabric
	- fabric-structure-api-v1 2.0.8+295197a7c8 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d95c8 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f55c8 via fabric
	- fabric-transfer-api-v1 1.5.5+b4f4f6cdc8 via fabric
	- fabricloader 0.12.9
	- io_leangen_geantyref_geantyref 1.3.11 via confabricate
	- java 17
	- minecraft 1.18.1
	- omega-config 1.0.8 via repurposed_structures
	- org_spongepowered_configurate-core 4.1.1 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.1 via confabricate
	- org_spongepowered_configurate-gson 4.1.1 via confabricate
	- org_spongepowered_configurate-hocon 4.1.1 via confabricate
	- repurposed_structures 3.1.8+1.18.0
	- servercore-fabric 1.2.5-1.18
[10:43:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/srv/minecraft/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[10:43:42] [main/INFO]: Compatibility level set to JAVA_16
[10:43:42] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:68) ~[fabric-server-launch.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
Caused by: java.lang.RuntimeException: Error creating Mixin config servercore.mixins.json for mod servercore-fabric
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config servercore.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
no server running on /tmp/tmux-973/minecraft
```

My personal conjecture is that this has something to do with the removal / changing of the logj4 plugin on 1.18.1, so simply bumping the mod version likely doesn't work for support.

**Comment by Wesley1808** [comment] 2021-12-10 17:21
Interesting. So a bug initially with the fabric loader, that was fixed in one of the most recent version for 1.18 managed to break again on 1.18.1.

Its fixed by setting a json value JAVA_17 -> JAVA_16, I'll push a fix for it.

**Comment by Wesley1808** [comment] 2021-12-10 17:27
It seems this is also fixed when using a newer version of the fabric installer. (not the loader, the installer)
Won't be pushing it to curseforge/modrinth as it shouldn't be necessary given thats the case.

**Closed by Wesley1808** 2021-12-10 17:27 UTC

**Comment by CozzyBro2** [comment] 2021-12-10 18:34
I've installed the latest version of the fabric installer, and reinstalled 0.12.10 for my server, i used the same modrinth version, and this issue does persist.

**Comment by Wesley1808** [comment] 2021-12-10 18:50
Strange. Can you try out the newest github actions build? I cannot reproduce this issue on my end - the server started up just fine after downloading the newest installer and reinstalling the server jars.

**Comment by CozzyBro2** [comment] 2021-12-10 18:57
Yep, using that build completely fixes the issue.

**Comment by TwoPointInfinity** [comment] 2021-12-24 19:59
i just grabbed the latest version from modrinth and came here just to say this but it seems fine now. Are you going to be pushing a new release on modrinth or would it be easier to just use your build from github?

**Comment by Wesley1808** [comment] 2021-12-24 20:01
Use the build from github actions if its an issue. I'm not entirely sure why this bug still occurs, but it most likely has to do with your local fabric / java installation.

**Comment by TwoPointInfinity** [comment] 2021-12-24 20:12
man i just grabbed the latest Fabric Installer 0.10.2 and this actually allows mods to have compatibility level 17 or 16. Why is fabric not telling us we need to update our installer? The old installer allows up updating to 1.18.1 but doesn't update its own compatibility level. Build from github works with it as well. thanks boss. 100% keep telling people to grab the latest installer if you need to from https://fabricmc.net/use/installer/ of ≥0.10.*
